framework:
    messenger:

        transports:
            async:
                dsn:  "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Bus\Message\BannerHitMessageInterface': async